- name: Build the go project
  changed_when: true
  ansible.builtin.command:
    cmd: go build -buildvcs=false
    chdir: /home/linuxuser/the_final_stockbot
- name: Move the binary
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /home/linuxuser/the_final_stockbot/the_final_stockbot
    dest: "/var/lib/{{ service_user_name }}/the_final_stockbot"
    mode: "0755"
  notify:
    - Reload systemd
