- name: Build the go project
  changed_when: true
  become: true
  ansible.builtin.command:
    cmd: go install ./cmd/litestream
    chdir: /root/litestream
- name: Move the binary
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /root/go/bin/litestream
    dest: "/usr/bin/litestream"
    mode: "0755"
- name: Move Systemd Service File
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /root/litestream/etc/litestream.service
    dest: /etc/systemd/system/litestream.service
    mode: "0644"
