---
- name: Set Password for linuxuser in PostgreSQL
  hosts: all
  remote_user: linuxuser
  become: true
  gather_facts: false

  vars_prompt:
    - name: db_password
      prompt: "Enter the password to set for the 'linuxuser' in PostgreSQL"
      private: yes

  tasks:
    - name: Set password for linuxuser in PostgreSQL
      community.postgresql.postgresql_user:
        name: linuxuser
        password: "{{ db_password }}"
        db: congress # Specify the database, though it might not be strictly necessary for user password
      become: true
      become_user: postgres
