---
- name: Setup Server
  hosts: all
  remote_user: linuxuser
  vars:
    variable_name: variable_value
    service_user_name: final_stockbot
    do_litestream: false
    static_root: /var/lib/final_stockbot/the_final_stockbot/static/
    server_name: www.dirtycongress.com

  tasks:
    - name: Install Packages
      become: true
      ansible.builtin.package:
        name:
          - bash-completion
          - htop
          - rsync
          - golang
          - nginx
          - git
          - git-lfs
          - graphviz
          - certbot
        state: present
        update_cache: true
    - name: Configure Firewall
      become: true
      community.general.ufw:
        rule: allow
        port: "80"
        comment: "Allow HTTP traffic"
        state: enabled
    - name: Configure Firewall
      become: true
      community.general.ufw:
        rule: allow
        port: "443"
        comment: "Allow HTTPS traffic"
        state: enabled

    - name: Configure Firewall
      become: true
      community.general.ufw:
        rule: deny
        port: "8080"
        comment: "Allow Proxy HTTP traffic"
        state: enabled

    - name: Install and Setup do_litestream
      when: do_litestream
      block:
        - name: Clone Litestream To Build From Source
          become: true
          ansible.builtin.git:
            repo: https://github.com/benbjohnson/litestream
            dest: /root/litestream
            version: main
          notify:
            - Install Litestream
        - name: Conditionally load the secrets for litestream
          ansible.builtin.include_vars: secrets.vault.yml
        - name: Template the litestream file
          become: true
          ansible.builtin.template:
            src: litestream.yml.j2
            dest: /etc/litestream.yml
            mode: "0644"
          notify:
            - Start and Reload Litestream via Systemd

    # Add a user and group
    - name: Add a service user
      ansible.builtin.user:
        name: "{{ service_user_name }}"
        state: present
        system: true
        shell: /bin/false
        home: "/var/lib/{{ service_user_name }}"

    - name: Clone my stockbot repository
      become: true
      ansible.builtin.git:
        repo: https://github.com/HSchmale16/the_final_stockbot
        dest: ~{{ service_user_name }}/the_final_stockbot
        version: master
      register: stockbot_git
      notify:
        - Build my application

    - name: Create nginx configuration
      become: true
      ansible.builtin.template:
        src: govt-stocks-site.nginx.j2
        dest: /etc/nginx/sites-available/govt-stocks-site
        mode: "0644"
      notify:
        - Reload nginx
    - name: Enable Nginx Site
      become: true
      ansible.builtin.file:
        src: /etc/nginx/sites-available/govt-stocks-site
        dest: /etc/nginx/sites-enabled/govt-stocks-site
        state: link


  ##### Handlers #####
  handlers:
    - name: Reload nginx
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
        name: nginx
        state: restarted
    - name: Reload systemd
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
        name: final-stockbot
        state: restarted
    - name: Build my application
      ansible.builtin.include_tasks:
        file: build-application.ansible.yml
    - name: Install Litestream
      ansible.builtin.include_tasks:
        file: install-litestream.ansible.yml
    - name: Start and Reload Litestream via Systemd
      become: true
      ansible.builtin.systemd:
        name: litestream
        state: restarted
        enabled: true
