---
- name: Setup Server
  hosts: all
  remote_user: root
  become: true
  vars:
    variable_name: variable_value

  tasks:
    - name: Install Monitoring First
      ansible.builtin.package:
        name:
          - htop
    - name: Install Packages
      ansible.builtin.package:
        name:
          - golang
          - rust-all
          - libonnx-dev
          - git
        state: present
        update_cache: true

    # Grab Dependency for hugot which we use for sentiment analysis
    - name: Check to build tokenizers
      stat:
        path: /usr/lib/libtokenizers.a
      register: tokenizers_library_stat
    - block:
        - name: Clone tokenizers repository
          git:
            repo: https://github.com/Knights-Analytics/tokenizers
            dest: /root/tokenizers
            version: main
        - name: Build project using cargo
          command:
            cmd: cargo build --release
            chdir: /root/tokenizers
        - name: Move Output Library
          copy:
            remote_src: true
            src: /root/tokenizers/target/release/libtokenizers.a
            dest: /usr/lib/libtokenizers.a
            mode: 0755
      when: 
        - not tokenizers_library_stat.stat.exists

    # Add a user and group
    - name: Add a service user
      ansible.builtin.user:
        name: final_stockbot
        state: present
        system: yes
        shell: /bin/false
        home: /var/lib/final_stockbot



    # Create the service
    - name: Create a systemd unit file
      ansible.builtin.template:
      src: final-stockbot.service.j2
      dest: /etc/systemd/system/final-stockbot.service
      notify:
        - Reload systemd

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
      daemon_reload: yes
      state: reloaded